function BMP = bmp_CHeBA_init (individual_original_DICOM_directory, cohort_BIDS_directory, BIDS_subject_label, varargin)
%
% varargin{1} = 'notRunningDicomCollection';
%
%

% Available modalities
% ======================================================================
	BMP.VCI.BIDS.modalities = {
										'T1MPRAGE'
										'T2'
										'FLAIR_3D'
										'SWI'
										'DWI'
										'ASL'
										'CVR_fmap'
										'CVR'
										'MP2RAGE'
										'DCE'
									};

	BMP.MAS2.BIDS.modalities = {
										'T1MPRAGE'
										'T1MEMPRAGE'
										'T2'
										'FLAIR_3D'
										'FLAIR_2D'
										'SWI'
										'DWI'
										'ASL_tc'
										'ASL_pwi'
										'ASL_relCBF'
										'rsBOLD'
										'rsBOLD_fmap'
									};



% Keywords in SeriesDescription
% ======================================================================
% The following keywords map all sequences to modalities, regardless of
% whether they are useful and/or to be converted to NIFTI.
% They are used in organising DICOM folders.
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.T1MPRAGE = 'T1_MPRAGE_0.8_iso';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.T2 = 'T2_spc_sag_0.8mm';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.FLAIR_3D = 't2_space_dark-fluid_sag_p2_ns-t2prep';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.SWI = 'greME7_p31_256_Iso1mm';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.DWI = 'DIFFUSION';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.ASL = 'asl_3d_tra_p2_iso_3mm_highres';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.CVR_fmap = 'gre_field_mapping 3.8mm';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.CVR = 'CVR_ep2d_bold 3.8mm TR1500 adaptive';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.MP2RAGE = 't1_mp2rage_sag_0.8x0.8x2';
	BMP.VCI.BIDS.seriesDescriptionKeywordToModalityMapping.DCE = 't1_vibe_sag_DCE_2mm XL FOV 40s temporal res';

	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.T1MPRAGE = 'T1_MPRAGE_0.8_iso';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.T1MEMPRAGE = 'T1_MEMPRAGE_64ch';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.T2 = 'T2_spc_sag_0.8mm_BW744';   % < -- this may change in the future
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.FLAIR_3D = 't2_space_dark-fluid_sag_p2_ns-t2prep';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.FLAIR_2D = 'Axial T2-FLAIR';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.SWI = 'greME7_p31_256_Iso1mm';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.DWI = 'DIFFUSION';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.ASL_tc = 'mTI16_800-3800_tgse_pcasl_3.4x3.4x4_14_31_2_24slc';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.ASL_pwi = 'Perfusion_Weighted';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.ASL_relCBF = 'relCBF';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.rsBOLD = 'fMRI _RESTING STATE_PA';
	BMP.MAS2.BIDS.seriesDescriptionKeywordToModalityMapping.rsBOLD_fmap = 'FMAP resting state fMRI';


% SeriesDescription to convert - VCI
% ======================================================================
% The following mappings only include those seq being useful and to be converted to NIFTI.

	% T1 MPRAGE
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.T1MPRAGE = {'T1_MPRAGE_0.8_iso'};
	BMP.VCI.BIDS.DICOM2BIDS.T1MPRAGE = struct(	'DataType',								'anat', ...
												'Modality',								'T1w', ...
												'Acquisition',							'MPRAGE0p8iso', ...
												'CorrespondingSeriesDescription',		'T1_MPRAGE_0.8_iso');

	% T2
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.T2 = {'T2_spc_sag_0.8mm'};
	BMP.VCI.BIDS.DICOM2BIDS.T2 = struct('DataType',								'anat', ...
										'Modality',								'T2w', ...
										'Acquisition',							'sagSPACE0p8iso', ...
										'CorrespondingSeriesDescription',		'T2_spc_sag_0.8mm');

	% FLAIR_3D
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.FLAIR_3D = {'t2_space_dark-fluid_sag_p2_ns-t2prep'};
	BMP.VCI.BIDS.DICOM2BIDS.FLAIR_3D = struct(	'DataType',							'anat', ...
												'Modality',							'FLAIR', ...
												'Acquisition',						'3dSPACE', ...
												'CorrespondingSeriesDescription',	't2_space_dark-fluid_sag_p2_ns-t2prep');

	% SWI
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.SWI = 	{
															'greME7_p31_256_Iso1mm_Mag'
														    'greME7_p31_256_Iso1mm_Pha'
														    'greME7_p31_256_Iso1mm_Qsm_Combined'
														    'greME7_p31_256_Iso1mm_SWI_Combined'
														    'greME7_p31_256_Iso1mm_SWI_mIP_Combined'
														    };
	BMP.VCI.BIDS.DICOM2BIDS.SWI_mag = struct(	'DataType',							'swi', ...
												'Modality',							'GRE', ...
												'Part',								'mag', ...
												'NumEchoes',						7, ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'yes', ...
												'AllVolumesAsSingle4D',				'no', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_Mag'); 
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_pha = struct(	'DataType',							'swi', ...
												'Modality',							'GRE', ...
												'Part',								'phase', ...
												'NumEchoes',						7, ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'yes', ...
												'AllVolumesAsSingle4D',				'no', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_Pha'); 
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_qsm = struct(	'DataType',							'swi', ...
												'Modality',							'Chimap', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_Qsm_Combined'); 
												% Ref : https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.suffixes.Chimap
												% 		https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_swi = struct(	'DataType',							'swi', ...
												'Modality',							'swi', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_SWI_Combined');
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_mip = struct(	'DataType',							'swi', ...
												'Modality',							'minIP', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_SWI_mIP_Combined');
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	% DWI
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.DWI =	{
															'AP_BLOCK_1_DIFFUSION_30DIR'
															'AP_BLOCK_2_DIFFUSION_30DIR'
															'AP_FMAP_for DIFFUSION'
															'PA_BLOCK_1_DIFFUSION_30DIR'
															'PA_BLOCK_2_DIFFUSION_30DIR'
															'PA_FMAP_for DIFFUSION'
															};
	BMP.VCI.BIDS.DICOM2BIDS.DWI_ap1 = struct(	'DataType',							'dwi', ...
												'Modality',							'dwi', ...
												'PhaseEncodingDirection',			'AP', ...
												'RunID',							'01', ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'no', ...
												'AllVolumesAsSingle4D',				'yes', ...
												'CorrespondingSeriesDescription',	'AP_BLOCK_1_DIFFUSION_30DIR');
												% Ref : https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data
	BMP.VCI.BIDS.DICOM2BIDS.DWI_ap2 = struct(	'DataType',							'dwi', ...
												'Modality',							'dwi', ...
												'PhaseEncodingDirection',			'AP', ...
												'RunID',							'02', ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'no', ...
												'AllVolumesAsSingle4D',				'yes', ...
												'CorrespondingSeriesDescription',	'AP_BLOCK_2_DIFFUSION_30DIR');
												% Ref : https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data
	BMP.VCI.BIDS.DICOM2BIDS.DWI_pa1 = struct(	'DataType',							'dwi', ...
												'Modality',							'dwi', ...
												'PhaseEncodingDirection',			'PA', ...
												'RunID',							'01', ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'no', ...
												'AllVolumesAsSingle4D',				'yes', ...
												'CorrespondingSeriesDescription',	'PA_BLOCK_1_DIFFUSION_30DIR');
												% Ref : https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data
	BMP.VCI.BIDS.DICOM2BIDS.DWI_pa2 = struct(	'DataType',							'dwi', ...
												'Modality',							'dwi', ...
												'PhaseEncodingDirection',			'PA', ...
												'RunID',							'02', ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'no', ...
												'AllVolumesAsSingle4D',				'yes', ...
												'CorrespondingSeriesDescription',	'PA_BLOCK_2_DIFFUSION_30DIR');
												% Ref : https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#diffusion-imaging-data
	BMP.VCI.BIDS.DICOM2BIDS.DWI_fmapAP = struct('DataType',							'fmap', ...
												'Modality',							'epi', ...
												'PhaseEncodingDirection',			'AP', ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'no', ...
												'AllVolumesAsSingle4D',				'yes', ...
												'Description',						'forDwi', ...
												'CorrespondingSeriesDescription',	'AP_FMAP_for DIFFUSION');
											% Ref : https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.suffixes.epi
											%		https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data
	BMP.VCI.BIDS.DICOM2BIDS.DWI_fmapPA = struct('DataType',							'fmap', ...
												'Modality',							'epi', ...
												'PhaseEncodingDirection',			'PA', ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'no', ...
												'AllVolumesAsSingle4D',				'yes', ...
												'Description',						'forDwi', ...
												'CorrespondingSeriesDescription',	'PA_FMAP_for DIFFUSION');
											% Ref : https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.suffixes.epi
											%		https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data

	% ASL
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.ASL = {'asl_3d_tra_p2_iso_3mm_highres'};
	BMP.VCI.BIDS.DICOM2BIDS.ASL = struct(	'DataType',								'perf', ...
											'Modality',								'asl', ...
											'HasMultipleVolumes',					'yes', ...
											'EachVolumeAsSeparate3D',				'no', ...
											'AllVolumesAsSingle4D',					'yes', ...
											'CorrespondingSeriesDescription',		'asl_3d_tra_p2_iso_3mm_highres');

	% CVR
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.CVR_fmap = {'gre_field_mapping 3.8mm'};
	BMP.VCI.BIDS.DICOM2BIDS.CVR_fmap = struct(	'DataType',							'fmap', ...
												'Modality',							'epi', ...
												'Description',						'forCvr', ...
												'CorrespondingSeriesDescription',	'gre_field_mapping 3.8mm'); % Unsure about this fmap.
																												% Assuming it is 'pepolar' fieldmap.
																												% Ref : https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar

	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.CVR = {'CVR_ep2d_bold 3.8mm TR1500 adaptive'};
	BMP.VCI.BIDS.DICOM2BIDS.CVR = struct(	'DataType',								'func', ...
											'Modality',								'bold', ...
											'Description',							'co2cvr', ...
											'HasMultipleVolumes',					'yes', ...
											'EachVolumeAsSeparate3D',				'no', ...
											'AllVolumesAsSingle4D',					'yes', ...
											'CorrespondingSeriesDescription',		'CVR_ep2d_bold 3.8mm TR1500 adaptive');

	% MP2RAGE
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.MP2RAGE = {
																't1_mp2rage_sag_0.8x0.8x2_INV1'
															    't1_mp2rage_sag_0.8x0.8x2_INV2'
															    't1_mp2rage_sag_0.8x0.8x2_T1_Images'
															    't1_mp2rage_sag_0.8x0.8x2_UNI_Images'
															};
	BMP.VCI.BIDS.DICOM2BIDS.MP2RAGE_unit1 = struct(	'DataType',							'anat', ...
													'Modality',							'UNIT1', ...
													'CorrespondingSeriesDescription',	't1_mp2rage_sag_0.8x0.8x2_UNI_Images', ...
													'IsDerivatives',					'yes', ...
													'Software',							'Siemens'); 
													% Ref : https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.suffixes.UNIT1
													%		https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#quantitative-maps-are-derivatives
	BMP.VCI.BIDS.DICOM2BIDS.MP2RAGE_t1map = struct(	'DataType',							'anat', ...
													'Modality',							'T1map', ...
													'CorrespondingSeriesDescription',	't1_mp2rage_sag_0.8x0.8x2_T1_Images', ...
													'IsDerivatives',					'yes', ...
													'Software',							'Siemens');
													% Ref : https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#quantitative-maps-are-derivatives
	BMP.VCI.BIDS.DICOM2BIDS.MP2RAGE_inv1 = struct(	'DataType',							'anat', ...
													'Modality',							'MP2RAGE', ...
													'Inversion',						'1', ...
													'CorrespondingSeriesDescription',	't1_mp2rage_sag_0.8x0.8x2_INV1');
													% Ref : https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html
	BMP.VCI.BIDS.DICOM2BIDS.MP2RAGE_inv2 = struct(	'DataType',							'anat', ...
													'Modality',							'MP2RAGE', ...
													'Inversion',						'2', ...
													'CorrespondingSeriesDescription',	't1_mp2rage_sag_0.8x0.8x2_INV2');
													% Ref : https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html

	% DCE
	BMP.VCI.BIDS.seriesDescriptionToConvertToNIFTI.DCE = {'t1_vibe_sag_DCE_2mm XL FOV 40s temporal res'};
	BMP.VCI.BIDS.DICOM2BIDS.DCE = struct(	'DataType',								'anat', ...
											'Modality',								'T1w', ...
											'ContrastEnhancingAgent',				'gd', ...
											'HasMultipleVolumes',					'yes', ...
											'EachVolumeAsSeparate3D',				'no', ...
											'AllVolumesAsSingle4D',					'yes', ...
											'CorrespondingSeriesDescription',		't1_vibe_sag_DCE_2mm XL FOV 40s temporal res');
											% Ref : https://bids-specification.readthedocs.io/en/latest/appendices/entities.html#ce
											% Note - not much info on DCE is found in BIDS specification. Modify when more info is found.


% SeriesDescription to convert - MAS2
% ======================================================================

	% MPRAGE
	BMP.MAS2.BIDS.seriesDescriptionToConvertToNIFTI.T1MPRAGE = {'T1_MPRAGE_0.8_iso'};
	BMP.MAS2.BIDS.DICOM2BIDS.T1MPRAGE = struct(	'DataType',								'anat', ...
												'Modality',								'T1w', ...
												'Acquisition',							'MPRAGE0p8iso', ...
												'CorrespondingSeriesDescription',		'T1_MPRAGE_0.8_iso');
	
	% MEMPRAGE
	BMP.MAS2.BIDS.seriesDescriptionToConvertToNIFTI.T1MEMPRAGE = {
																	'T1_MEMPRAGE_64ch'
																	'T1_MEMPRAGE_64ch RMS'
																};
	BMP.MAS2.BIDS.DICOM2BIDS.T1MEMPRAGE_echos = struct(	'DataType',							'anat', ...
														'Modality',							'T1w', ...
														'Acquisition',						'MEMPRAGE', ...
														'NumEchoes',						4, ...
														'HasMultipleVolumes',				'yes', ...
														'EachVolumeAsSeparate3D',			'no', ...
														'AllVolumesAsSingle4D',				'yes', ...
														'CorrespondingSeriesDescription',	'T1_MEMPRAGE_64ch');
	BMP.MAS2.BIDS.DICOM2BIDS.T1MEMPRAGE_rms = struct(	'DataType',							'anat', ...
														'Modality',							'T1w', ...
														'Acquisition',						'MEMPRAGE', ...
														'HasMultipleVolumes',				'no', ...
														'CorrespondingSeriesDescription',	'T1_MEMPRAGE_64ch RMS');

	% T2
	BMP.MAS2.BIDS.seriesDescriptionToConvertToNIFTI.T2 = {'T2_spc_sag_0.8mm'};
	BMP.MAS2.BIDS.DICOM2BIDS.T2 = struct(	'DataType',							'anat', ...
											'Modality',							'T2w', ...
											'Acquisition',						'sagSPACE0p8isoBW744', ...
											'CorrespondingSeriesDescription',	'T2_spc_sag_0.8mm_BW744'); % <== this may be changed in the future.

	% FLAIR_3D
	BMP.MAS2.BIDS.seriesDescriptionToConvertToNIFTI.FLAIR_3D = {'t2_space_dark-fluid_sag_p2_ns-t2prep'};
	BMP.MAS2.BIDS.DICOM2BIDS.FLAIR_3D = struct(	'DataType',							'anat', ...
												'Modality',							'FLAIR', ...
												'Acquisition',						'3dSPACE', ...
												'CorrespondingSeriesDescription',	't2_space_dark-fluid_sag_p2_ns-t2prep');

	% FLAIR_2D
	BMP.MAS2.BIDS.seriesDescriptionToConvertToNIFTI.FLAIR_2D = {'Axial T2-FLAIR'};
	BMP.MAS2.BIDS.DICOM2BIDS.FLAIR_2D = struct(	'DataType',							'anat', ...
												'Modality',							'FLAIR', ...
												'Acquisition',						'axSPACE', ...
												'CorrespondingSeriesDescription',	'Axial T2-FLAIR');

	% SWI
	BMP.MAS2.BIDS.seriesDescriptionToConvertToNIFTI.SWI = 	{
															'greME7_p31_256_Iso1mm_Mag'
														    'greME7_p31_256_Iso1mm_Pha'
														    'greME7_p31_256_Iso1mm_Qsm_Combined'
														    'greME7_p31_256_Iso1mm_SWI_Combined'
														    'greME7_p31_256_Iso1mm_SWI_mIP_Combined'
														    };	% ---=== !!! ===---
														    	% NOTE that filtered and non-filtered phase images were both named 'greME7_p31_256_Iso1mm_Pha'
														    	% Only series numbers were different.
														    	% ---=== !!! ===---
	BMP.VCI.BIDS.DICOM2BIDS.SWI_mag = struct(	'DataType',							'swi', ...
												'Modality',							'GRE', ...
												'Part',								'mag', ...
												'NumEchoes',						7, ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'yes', ...
												'AllVolumesAsSingle4D',				'no', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_Mag'); 
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_pha = struct(	'DataType',							'swi', ...
												'Modality',							'GRE', ...
												'Part',								'phase', ...
												'NumEchoes',						7, ...
												'HasMultipleVolumes',				'yes', ...
												'EachVolumeAsSeparate3D',			'yes', ...
												'AllVolumesAsSingle4D',				'no', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_Pha'); 
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_qsm = struct(	'DataType',							'swi', ...
												'Modality',							'Chimap', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_Qsm_Combined'); 
												% Ref : https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.suffixes.Chimap
												% 		https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_swi = struct(	'DataType',							'swi', ...
												'Modality',							'swi', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_SWI_Combined');
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

	BMP.VCI.BIDS.DICOM2BIDS.SWI_mip = struct(	'DataType',							'swi', ...
												'Modality',							'minIP', ...
												'CorrespondingSeriesDescription',	'greME7_p31_256_Iso1mm_SWI_mIP_Combined');
												% Ref : https://docs.google.com/document/d/1kyw9mGgacNqeMbp4xZet3RnDhcMmf4_BmRgKaOkO2Sc/edit#heading=h.mqkmyp254xh6

























	

	BMP.VCI.BIDS.individualOriginalDicomDirectory = individual_original_DICOM_directory;
	BMP.VCI.BIDS.individualBmpDicomDirectory = fullfile(fileparts(individual_original_DICOM_directory),'DICOM_BMP');

	BMP.VCI.BIDS.subject_label = BIDS_subject_label;

	BMP.VCI.BIDS.cohortBIDSdirectory  = cohort_BIDS_directory;
	BMP.VCI.BIDS.individualBIDSdirectory = fullfile (BMP.VCI.BIDS.cohortBIDSdirectory, ['sub-' BMP.VCI.BIDS.subject_label]);

	if nargin == 4 && strcmp (varargin{1}, 'notRunningDicomCollection')
		fprintf ('%s : Not running dicomCollection.\n', mfilename);
	else
		BMP.VCI.BIDS.dicomCollection = dicomCollection (individual_original_DICOM_directory, "IncludeSubfolders", true); 	% Note that DICOM folder is used
																												% as input, instead of DICOMDIR
																												% file. This is because output
																												% from dicomCollection with DICOMDIR
																												% will miss some series.
	end

	BMP.VCI.BIDS.stringInFilenamesInDicomCollectionstrToBeReplaced = '/home/jiyang/Work';
	BMP.VCI.BIDS.stringInFilenamesInDicomCollectionstrToReplaceTo  = '/data/vci/pilotPS';

end