#!/bin/bash

#====================================
# BRAIN_Fieldmap_generateFieldmap.sh
#====================================
#
# DESCRIPTION
# ------------
# This script converts the two (magnitude + phase) images for two
# echos to the field map, ready for correcting fMRI distortion
#
#
# DATA PREPARATION 
# -----------------
# The two fieldmap nii files (i.e. two echos) should be named as:
# ID_fieldmap_e1.nii
# ID_fieldmap_e2.nii
# And saved in the same folder (i.e. studyFolder)
#
#
# USAGE
# -----
# <PATH TO BRAIN_processing_pipeline>/Fieldmap/BRAIN_Fieldmap_generateFieldmap.sh ID studyFolder
#
#
# References
# ----------
# https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=fsl;b7eac096.1310
#
#
# Written by Dr. Jiyang Jiang on March 2018
#


# source fsl configurations
. ${FSLDIR}/etc/fslconf/fsl.sh


getFieldmap(){

	# Passing arguments
	ID=$1
	studyFolder=$2


	# split fieldmap nii file generated by scanner for each of the 2 echos
	# Volume 1 is magnitute map
	# Volume 2 is phase map
	# fslsplit output in working dir
	cd ${studyFolder}

	fslsplit ${studyFolder}/${ID}_fieldmap_e1.nii
	mv ${studyFolder}/vol0000.nii.gz ${studyFolder}/${ID}_fieldmap_e1_mag.nii.gz
	mv ${studyFolder}/vol0001.nii.gz ${studyFolder}/${ID}_fieldmap_e1_pha.nii.gz

	fslsplit ${studyFolder}/${ID}_fieldmap_e2.nii
	mv ${studyFolder}/vol0000.nii.gz ${studyFolder}/${ID}_fieldmap_e2_mag.nii.gz
	mv ${studyFolder}/vol0001.nii.gz ${studyFolder}/${ID}_fieldmap_e2_pha.nii.gz

	cd -
	
	# non-brain tissue removal using BET
	# on magnitute maps first, and then use mask for phase maps
	bet ${studyFolder}/${ID}_fieldmap_e1_mag.nii.gz ${studyFolder}/${ID}_fieldmap_e1_mag_brain
	fslmaths ${studyFolder}/${ID}_fieldmap_e1_pha.nii.gz \
				-mas ${studyFolder}/${ID}_fieldmap_e1_mag_brain \
				${studyFolder}/${ID}_fieldmap_e1_pha_brain

	bet ${studyFolder}/${ID}_fieldmap_e2_mag.nii.gz ${studyFolder}/${ID}_fieldmap_e2_mag_brain
	fslmaths ${studyFolder}/${ID}_fieldmap_e2_pha.nii.gz \
				-mas ${studyFolder}/${ID}_fieldmap_e2_mag_brain \
				${studyFolder}/${ID}_fieldmap_e2_pha_brain


	# Scale each phase map to -pi~+pi by deviding by 8192 and multiply by 3.14159
	fslmaths ${studyFolder}/${ID}_fieldmap_e1_pha_brain \
														-div 8192 \
														-mul 3.14159 \
														${studyFolder}/${ID}_fieldmap_e1_pha_brain_rad \
														-odt float

	fslmaths ${studyFolder}/${ID}_fieldmap_e2_pha_brain \
														-div 8192 \
														-mul 3.14159 \
														${studyFolder}/${ID}_fieldmap_e2_pha_brain_rad \
														-odt float


	# Unwrapping phase maps with prelude
	prelude -a ${studyFolder}/${ID}_fieldmap_e1_mag_brain \
			-p ${studyFolder}/${ID}_fieldmap_e1_pha_brain_rad \
			-o ${studyFolder}/${ID}_fieldmap_e1_pha_brain_rad_unwrap

	prelude -a ${studyFolder}/${ID}_fieldmap_e2_mag_brain \
			-p ${studyFolder}/${ID}_fieldmap_e2_pha_brain_rad \
			-o ${studyFolder}/${ID}_fieldmap_e2_pha_brain_rad_unwrap


	# Generating fieldmap in rad/s
	# by calculating the difference between phase maps
	# TE for echo 1 is 0.008 and echo 2 is 0.02 (in sec)
	fslmaths ${studyFolder}/${ID}_fieldmap_e2_pha_brain_rad_unwrap \
				-sub ${studyFolder}/${ID}_fieldmap_e1_pha_brain_rad_unwrap \
				-div 0.012 \
				${studyFolder}/${ID}_fieldmap_radpers_brain \
				-odt float

	# Regularising the fieldmap with FUGUE
	# Step 1: Gaussian smoothing
	fugue --loadfmap=${studyFolder}/${ID}_fieldmap_radpers_brain \
			-s 1 \
			--savefmap=${studyFolder}/${ID}_fieldmap_radpers_brain_regularisationStep1

	# Step 2: despiking
	fugue --loadfmap=${studyFolder}/${ID}_fieldmap_radpers_brain_regularisationStep1 \
			--despike \
			--savefmap=${studyFolder}/${ID}_fieldmap_radpers_brain_regularisationStep2

	# Step 3: median filtering
	fugue --loadfmap=${studyFolder}/${ID}_fieldmap_radpers_brain_regularisationStep2 \
			-m \
			--savefmap=${studyFolder}/${ID}_fieldmap_radpers_brain_regularisationFinal
}


getFieldmap $1 $2