function L_lv_spm_genDARTELbrainAndMask (cohortFolder, N_grps, CNSpath, SPMpath)

addpath ([CNSpath '/Scripts'], SPMpath);

for i = 1 : N_grps
	list_c1 = dir ([cohortFolder '/spm/grp' num2str(i) '/c1*_anat.nii']);

	[N_subj, ~] = size (list_c1);

	wanat_cellArr = cell (N_subj,1);
	wc1_cellArr = cell (N_subj,1);
	wc2_cellArr = cell (N_subj,1);
	wc3_cellArr = cell (N_subj,1);

	for j = 1 : N_subj
		subjID = strsplit (list_c1(j).name,'_');
		subjID = subjID{1};
		subjID = strsplit (subjID, 'c1');
		subjID = subjID{2};

		wanat_cellArr{j,1} = [list_c1(j).folder '/w' subjID '_anat.nii,1'];
		wc1_cellArr{j,1} = [list_c1(j).folder '/wc1' subjID '_anat.nii'];
		wc2_cellArr{j,1} = [list_c1(j).folder '/wc2' subjID '_anat.nii'];
		wc3_cellArr{j,1} = [list_c1(j).folder '/wc3' subjID '_anat.nii'];
	end

	group_head = CNSP_imgCal ('avg', ...
							   [cohortFolder '/spm/grp' num2str(i)], ...
							   ['grp' num2str(i) '_head'], ...
							   N_subj, ...
							   wanat_cellArr);



	group_wc1 = CNSP_imgCal ('avg', ...
							   [cohortFolder '/spm/grp' num2str(i)], ...
							   ['grp' num2str(i) '_wc1'], ...
							   N_subj, ...
							   wc1_cellArr);

	group_wc2 = CNSP_imgCal ('avg', ...
							   [cohortFolder '/spm/grp' num2str(i)], ...
							   ['grp' num2str(i) '_wc2'], ...
							   N_subj, ...
							   wc2_cellArr);

	group_wc3 = CNSP_imgCal ('avg', ...
							   [cohortFolder '/spm/grp' num2str(i)], ...
							   ['grp' num2str(i) '_wc3'], ...
							   N_subj, ...
							   wc3_cellArr);

	% add ventricles to grp?_brain and grp?_brain_mask
	system (['fslmaths ' group_wc3  ' ' ...
						 '-mas ' CNSpath '/Templates/DARTEL_ventricle_distance_map/DARTEL_ventricle_65to75 ' ...
						 '-dilM -dilM -dilM ' ...
						 list_c1(1).folder '/grp' num2str(i) '_vent']);

	system (['fslmaths ' group_wc1 ' ' ...
						 '-add ' group_wc2 ' ' ...
						 '-add ' list_c1(1).folder '/grp' num2str(i) '_vent ' ...
						 '-thr 0.5 ' ...
						 '-bin ' ...
						 '-dilM ' ...
						 '-bin ' ...
						 list_c1(1).folder '/grp' num2str(i) '_brain_mask']);

	system (['fslmaths ' list_c1(1).folder '/grp' num2str(i) '_head ' ...
						 '-mas ' list_c1(1).folder '/grp' num2str(i) '_brain_mask ' ...
						 list_c1(1).folder '/grp' num2str(i) '_brain']);

end