function varargout = bmp_ADNI (operation_mode, varargin)
%
% DESCRIPTION
% ====================================================================================
%
%   bmp_ADNI contains a few shortcuts for ADNI cohort, including processing ADNI study
%   data downloaded from ADNI website, creating or retrieving existing DICOM-to-BIDS 
%   mappings, running dcm2niix to convert DICOM to BIDS, and diagnosing/check any 
%   missing by examining actual DICOM folders or comparing with Clinica outputs.
%
%   Note that since ADNI dataset has multiple sessions (i.e., timepoints) and subject
%   ID and scan date need to be used to identify session label, we specify ADNI
%   DICOM-to-BIDS mappings in individual-level.
%
%
%
% ARGUMENTS
% ====================================================================================
%
%   bmp_ADNI can be ran in the following modes:
%
%
%     'initiate' mode
%     +++++++++++++++++++++++++++++++++
%
%       Call bmp_ADNI_studyData.m to process ADNI study data, and generate
%       /path/to/BrainMRIpipelines/BIDS/bmp_ADNI.mat. The MAT file saves
%       MRI_master, DEM_master, forDICOM2BIDS, and forBIDSpptsTsv.
%
%         operation_mode = 'initiate';
%
%         varargout{1} = DEM_master;
%         varargout{2} = MRI_master;
%         varargout{3} = forDICOM2BIDS;
%         varargout{4} = forBIDSpptsTsv;
%
%
%     'create' or 'create_mapping' mode 
%     +++++++++++++++++++++++++++++++++
%       
%        This mode is used to generate DICOM-to-BIDS mappings, and append the mappings 
%        to /path/to/BrainMRIpipelines/BIDS/bmp_ADNI.mat.
%
%        operation_mode = 'create'; % or 'create_mapping'
%
%        varargout{1} = DICOM2BIDS;
%
%
%     'retrieve' or 'retrieve_mapping' mode
%     +++++++++++++++++++++++++++++++++++++
%
%        This mode load /path/to/BrainMRIpipelines/BIDS/bmp_ADNI.mat to retrieve 
%        the predefiend mappings.
%
%        operation_mode = 'retrieve'; % or 'retrieve_mapping'
%
%        varargout{1} = DICOM2BIDS;
%
%
%     'dcm2niix' or 'run_dcm2niix' mode
%     +++++++++++++++++++++++++++++++++
%
%        This mode load bmp_ADNI_dcm2niixcmd.mat file generated by bmp_BIDSgenerator
%        to run dcm2niix for conversion. varargin{1} is /path/to/bmp_ADNI_dcm2niix.mat.
%        Default is /path/to/BrainMRIpipelines/BIDS/bmp_ADNI_dcm2niix.mat.
%
%
%     'refresh' or 'refresh_mat_files' mode
%     +++++++++++++++++++++++++++++++++++++
%
%        This mode refresh all necessary MAT files for new 
%        ADNI/bmp_ADNI_forDicom2BidsMapping.mat.
%
%        varargin{1} = DICOM directory
%        varargin{2} = BIDS directory
%
%
%     'prepare'
%
%
%     'checkback'
%
%
%
% SUPPORTED MODALITIES
% ====================================================================================
%
%   - T1w
%   - FLAIR
%   - asl
%
%
% HISTORY
% ====================================================================================
%
%   05 December 2022 - first version.
%
%   09 December 2022 - bmp_BIDSgenerator needs scalar input. Therfore, change
%                      DICOM2BIDS(i) to ADNI.DICOM2BIDS(i).
%
%
% KNOWN LIMITATIONS
% ====================================================================================
%
%  - Depending on VISCODE to identify multiply runs in the same session.
%
%  - Assumes max of 2 runs for each session.
%
%


	BMP_PATH = getenv ('BMP_PATH');



	% possible keywords in DICOM sequence name for each modality in ADNI
	possibleASLkeywords = 	{
							'ASL'
							'cerebral blood flow'
							'perfusion'
							'MoCoSeries'
							};						% 16Dec2022 : 	According to ASL QC files, SEQUENCE with
													% 				'MoCoSeries' corresponds to ASL.

	possibleT1keywords = 	{
							'MPRAGE'
							'T1'
							'IR-SPGR'
							'IR-FSPGR'
							'MP-RAGE'
							'MP RAGE'
							};

	possibleFLAIRkeywords = {
							'FLAIR'
							};



	switch operation_mode


		case 'initiate'

			clear all
			clc

			fprintf ('%s : Running in ''initiate'' mode.\n', mfilename);
			fprintf ('%s : Calling bmp_ADNI_studyData.m to process ADNI study data ... ', mfilename);

			[varargout{1}, varargout{2}, varargout{3}, varargout{4}] = bmp_ADNI_studyData;

			fprintf ('DONE!\n');


		case {'create'; 'create_mapping'}

			if nargin == 2 && endsWith(varargin{1},'.mat')
				output = varargin{1};
			else
				output = fullfile (BMP_PATH, 'BIDS', 'bmp_ADNI.mat');
			end

			fprintf ('%s : Running in ''create'' mode. Will save DICOM2BIDS mapping to %s.\n',mfilename,output);

			fprintf ('%s : Loading bmp_ADNI.mat ... ', mfilename);

			ADNI_mat = load (fullfile (BMP_PATH, 'BIDS', 'bmp_ADNI.mat'));

			fprintf ('DONE!\n', mfilename);

			forDICOM2BIDS = ADNI_mat.forDICOM2BIDS;
			
			fprintf ('%s : Start to create DICOM2BIDS mapping.\n', mfilename);


			% Initialise
			% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			SUBJECT = strcat('ADNI',erase(forDICOM2BIDS.SID,'_'));
			SESSION = forDICOM2BIDS.VISCODE;
			DATATYPE = cell (size (forDICOM2BIDS,1),1);
			DATATYPE(:,1) = {'UNKNOWN'};
			MODALITY = cell (size (forDICOM2BIDS,1),1);
			MODALITY(:,1) = {'UNKNOWN'};
			RUN = ones (size (forDICOM2BIDS,1),1);
			ACQUISITION = cell (size (forDICOM2BIDS,1),1);
			ACQUISITION(:,1) = {'UNKNOWN'};
			SEQUENCE = forDICOM2BIDS.SEQUENCE;
			PATIENTID = forDICOM2BIDS.SID;
			STUDYDATE = strrep(cellstr(forDICOM2BIDS.SCANDATE),'-','');
			IMAGEUID = forDICOM2BIDS.IMAGEUID;
			DICOMSUBDIR = strrep(strrep(strrep(forDICOM2BIDS.SEQUENCE,' ','_'),'(','_'),')','_');


			% Modality
			% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			MODALITY(find(contains(SEQUENCE,possibleT1keywords,		'IgnoreCase',true)),1) = {'T1w'};
			MODALITY(find(contains(SEQUENCE,possibleFLAIRkeywords,	'IgnoreCase',true)),1) = {'FLAIR'};
			MODALITY(find(contains(SEQUENCE,possibleASLkeywords,	'IgnoreCase',true)),1) = {'asl'};

			% Datatype
			% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			DATATYPE(find(strcmp(MODALITY,'T1w')),1) 	= {'anat'};
			DATATYPE(find(strcmp(MODALITY,'FLAIR')),1) 	= {'anat'};
			DATATYPE(find(strcmp(MODALITY,'asl')),1) 	= {'perf'};

			% Run
			% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			RUN(find(contains(SEQUENCE,{'repeat', 'repe', 'rpt','rep', 'repea'},'IgnoreCase',true)),1) = 2;

			for i = 1 : 9 												% support up to 9 runs
				forDICOM2BIDS_temp = table(	forDICOM2BIDS.SID,...
											forDICOM2BIDS.SCANDATE,...
											forDICOM2BIDS.VISCODE,...
											forDICOM2BIDS.SEQUENCE,...
											RUN);
				forDICOM2BIDS_temp.Properties.VariableNames = {'SID';'SCANDATE';'VISCODE';'SEQUENCE';'RUN'};
				[~, uniqIdx] = unique(forDICOM2BIDS_temp);
				RUN(setdiff(1:size(forDICOM2BIDS_temp,1), uniqIdx),1) = i+1;
			end

			RUN(find(strcmp(SEQUENCE,'Axial 3D PASL (Eyes Open) REPEAT')),1) = 1; 	% this happened once for 036_S_6316 in 2019-08-13. However, we cannot
																					% find another ASL on the same day therefore, we are not assigning
																					% 'run' entity although it said 'REPEAT'.
																					%
			RUN(find(strcmp(SEQUENCE,'Axial 3D PASL (Eyes Open) REPEAT')),1) = 2;	% 16Dec2022 : Run 1 does exist in DICOM, although not
																					%             documented in study data. Therefore,
																					%             resuming RUN = 2. Run 1 should be converted
																					%             in 'checkback' mode.


			% Acquisition
			% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			ACQUISITION(find(contains(SEQUENCE,'Axial 3D PASL',										'IgnoreCase',true)),1) = {'ax3dpasl'}; 
			ACQUISITION(find(contains(SEQUENCE,{'Ax 3D pCASL'; 'Axial 3D pCASL';'Axial_3D_pCASL'},	'IgnoreCase',true)),1) = {'ax3dpcasl'};
			ACQUISITION(find(contains(SEQUENCE,'Axial 2D PASL',										'IgnoreCase',true)),1) = {'ax2dpasl'};
			ACQUISITION(find(contains(SEQUENCE,'tgse_pcasl_PLD2000',								'IgnoreCase',true)),1) = {'tgsepcasl2000pld'}; 
			ACQUISITION(find(contains(SEQUENCE,'Cerebral Blood Flow',								'IgnoreCase',true)),1) = {'cbf'};
			ACQUISITION(find(contains(SEQUENCE,'Perfusion_Weighted',								'IgnoreCase',true)),1) = {'perfwei'}; 	% Note over 3000 perfusion-
																																			% weighted and relCBF cannot
																																			% find SID. Therefore, DICOM2BIDS
																																			% for these images is not able
																																			% to establish from study data.
																																			% This should be resolved in
																																			% 'checkback' mode to find
																																			% mapping based on existing
																																			% DICOM.

			ACQUISITION(find(contains(SEQUENCE, {'MPRAGE';'MP RAGE';'MP-RAGE'}, 'IgnoreCase', true)),1) = {'mprage'};
			ACQUISITION(find(contains(SEQUENCE, 'IR-SPGR',						'IgnoreCase', true)),1) = {'irspgr'};
			ACQUISITION(find(contains(SEQUENCE, 'IR-FSPGR',						'IgnoreCase', true)),1) = {'irfspgr'}; 	% keywords in SEQUENCE, such as '3D' and 'SAGITTAL'
																														% are not included in ACQUISITION for now.

			ACQUISITION(find(contains(SEQUENCE, {'AX';'AXIAL'},					'IgnoreCase', true))) = {'ax'};
			ACQUISITION(find(contains(SEQUENCE, {'Sagittal'; 'SAG'},			'IgnoreCase', true))) = {'sag'}; % keywords '3D' in SEQUENCE not included in ACQUISITION for now.


			DICOM2BIDS = table (SUBJECT,SESSION,DATATYPE,MODALITY,RUN,ACQUISITION,SEQUENCE,PATIENTID,STUDYDATE,IMAGEUID,DICOMSUBDIR);



			fprintf ('%s : ADNI DICOM2BIDS mapping has been created.\n', mfilename);

			fprintf ('%s : Saving ADNI DICOM2BIDS to %s ... ', mfilename, output);

			save (output, 'DICOM2BIDS', '-append');

			fprintf ('DONE!\n');

			varargout{1} = DICOM2BIDS;




		case {'retrieve'; 'retrieve_mapping'}

			ADNI_mat = fullfile (BMP_PATH, 'BIDS', 'bmp_ADNI.mat');
			
			fprintf ('%s : Running in ''retrieve'' mode. Will retrieve DICOM2BIDS mapping from %s.\n',mfilename,ADNI_mat);

			fprintf ('%s : Loading %s ... ', mfilename, ADNI_mat);

			varargout{1} = load(ADNI_mat).DICOM2BIDS;

			fprintf ('DONE!\n');




		case {'dcm2niix'; 'run_dcm2niix'}

			if nargin == 2 && isfile (varargin{1}) && endsWith(varargin{1},'.mat')
				dcm2niixcmdmat = varargin{1};
			else
				dcm2niixcmdmat = fullfile (BMP_PATH, 'BIDS', 'bmp_ADNI_dcm2niix.mat');
			end

			dcm2niix = load(dcm2niixcmdmat).dcm2niix;
			

			for i = 1 : size(dcm2niix.cmd,1)

				if ~ isfolder (dcm2niix.BIDSoutputdir{i,1})

					status = mkdir (dcm2niix.BIDSoutputdir{i,1});

					if ~ status

						dcm2niix.BIDSmkdirStatus{i,1} = 'failed creating BIDS folder';

						fprintf(2, '%s : Creating BIDS directory ''%s'' failed. This may be because you don''t have the directory structure specified in bmp_ADNI_dcm2niixcmd.mat. You may need to run bmp_BIDSgenerator with proper BIDS_directory argument.\n', mfilename, dcm2niix.BIDSoutputdir{i,1});

						continue

					else

						dcm2niix.BIDSmkdirStatus{i,1} = 'BIDS folder created successfully';

					end

				else

					dcm2niix.BIDSmkdirStatus{i,1} = 'BIDS folder already exists';

				end

				fprintf ('%s : (%d / %d) : Running dcm2niix to convert ''%s'' to ''%s''.nii ...', mfilename, i, size (dcm2niix.DICOMinputdir,1), dcm2niix.DICOMinputdir{i,1}, fullfile(dcm2niix.BIDSoutputdir{i,1}, dcm2niix.BIDSniibasename{i,1}));

				[dcm2niix.cmdstatus{i,1}, dcm2niix.cmdout{i,1}] = system (dcm2niix.cmd{i,1});

				if contains (dcm2niix.cmdout{i,1}, 'warning', 'IgnoreCase', true)

					dcm2niix.warnings{i,1} = true;

				else

					dcm2niix.warnings{i,1} = false;

				end

				fprintf (' DONE!\n');

			end

			fprintf('%s : Saving dcm2niix commands and command outputs to bmp_ADNI_dcm2niix.mat.\n', mfilename);

			save (dcm2niixcmdmat, 'dcm2niix');

			varargout{1} = dcm2niix;


		case {'refresh'; 'refresh_mat_files'} % refresh mode is for internal testing.

			ADNI = bmp_ADNI ('create'); % create DICOM2BIDS

			[~] = bmp_BIDSgenerator ('ADNI', ADNI, varargin{1}, varargin{2});

			%% not running dcm2niix in refresh mode.


		case {'prepare'} % prepare for real run

			ADNI = bmp_ADNI ('retrieve');

			[~] = bmp_BIDSgenerator ('ADNI', ADNI, varargin{1}, varargin{2}, 'MatOutDir', fullfile (varargin{2}, 'code', 'BMP'));


		case {'checkback'} 	% using info from MRI scans (e.g., ???_S_???? IDs) and comparing with info
							% in MRI_master table in bmp_ADNI.mat, in order to try to savage some of
							% the scans.

	end

end
	
